# Generated by Django 5.0 on 2024-11-16 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_users',
            field=models.ManyToManyField(db_table='follows', related_name='follower_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
