# Generated by Django 5.0.2 on 2024-10-02 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_table'),
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_user_set',
            field=models.ManyToManyField(related_name='follower_user_set', through='follows.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
