# Generated by Django 5.0 on 2024-11-10 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_user_set',
            field=models.ManyToManyField(db_table='follows', related_name='follower_user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
